### ISSUE TITLE
HA crashed, here's some log info.

### ISSUE THREAD

**Issue by Jese44** [warrior25/HA-Nysse#10]
I can't tell if this was related to freezing and forced automatic reboot of the HA but anyway timestamp matches the time of freezing.

Loginfo is from home-assistant.log.1 after reboot. there were 3 of these same lines in a row
V1.2.2.
`2024-11-20 22:00:12.584 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/www/nysse/stops.txt',) inside the event loop by custom integration 'nysse' at custom_components/nysse/fetch_api.py, line 219: with open(file_path, newline="", encoding="utf-8") as csvfile: (offender: /config/custom_components/nysse/fetch_api.py, line 219: with open(file_path, newline="", encoding="utf-8") as csvfile:), please create a bug report at https://github.com/warrior25/HA-Nysse/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/nysse/sensor.py", line 193, in async_update
    self._journeys = await get_stop_times(
  File "/config/custom_components/nysse/fetch_api.py", line 283, in get_stop_times
    await _fetch_gtfs()
  File "/config/custom_components/nysse/fetch_api.py", line 61, in _fetch_gtfs
    await _read_csv_to_db()
  File "/config/custom_components/nysse/fetch_api.py", line 86, in _read_csv_to_db
    stops = _parse_csv_file(_get_dir_path() + "stops.txt")
  File "/config/custom_components/nysse/fetch_api.py", line 219, in _parse_csv_file
    with open(file_path, newline="", encoding="utf-8") as csvfile:`

**Comment by aqlalp** [comment]
I got the same issue
